[[headers]]
for = "/*"
[headers.values]
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, DELETE"
  Access-Control-Allow-Headers = "Content-Type, Authorization"
  Cross-Origin-Embedder-Policy = "require-corp"
  Cross-Origin-Opener-Policy = "same-origin"